name: Build Maven

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
env:
  ARTIFACTORY_URL: https://telefonicainnovationalpha.jfrog.io/artifactory/health-maven/com/koa/data/kafka
  ARTIFACTORY_USER: svc-data
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set env vars
        run: |
          echo "PACKAGE_NAME=$(cat pom.xml | grep artifactId | head -n 1 | cut -f2 -d\> | cut -f1 -d\<)" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(cat pom.xml | grep \<version\> | head -n 1 | cut -f2 -d\> | cut -f1 -d\<)" >> $GITHUB_ENV
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Maven tests
        run: mvn test verify
      - name: Build with Maven
        run: mvn package
      - name: upload to jfrog
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          curl -u ${{ env.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_TOKEN }} \
          -X PUT "${{ env.ARTIFACTORY_URL }}/${{ env.PACKAGE_NAME}}/${{ env.PACKAGE_VERSION}}/${{env.PACKAGE_NAME}}-${{env.PACKAGE_VERSION}}.jar" \
          -T ./target/${{env.PACKAGE_NAME}}-${{env.PACKAGE_VERSION}}.jar
